TARGET = snes.dll
HEADERS = $(wildcard */*.h)
INCDIRS = -I.
CFLAGS += -O3 -g -Wall -std=c99 -msse2

SOURCES = $(wildcard */*.c)
OBJ = $(SOURCES:.c=.o)
TEST_OBJ = main_test.o

CC = gcc

ifneq ($(DEBUG),)
   CFLAGS += -DSSNES_DEBUG
endif

all: lib

lib: $(TARGET)

%.o: %.c $(HEADERS)
	$(CC) -c -o $@ $< $(CFLAGS) $(INCDIRS)

$(TARGET): $(OBJ)
	$(CC) -shared -o $@ $(OBJ) $(LDFLAGS)


clean:
	rm -f $(OBJ) $(TARGET) $(TEST_OBJ) $(TEST_TARGET)

.PHONY: clean lib
